### ISSUE TITLE
delay of deregister is obvious under a big cluster

### ISSUE THREAD

**Issue by jyaguo** [tkestack/lb-controlling-framework#54]

**Comment by ilyee** [comment]
#55

**Comment by ilyee** [comment]
@jyaguo add some reasons for why we need this?

**Comment by jyaguo** [comment]
The process of deregister backend is asynchronous. High latency may occurs when the controller running in a big cluster. The backend pod may be deleted during the latency, which may be intolerable. We fix it to deregister the backend immediately when the pod is deleting.

**Comment by ilyee** [comment]
merged
